name: Pull-Request-main
on:
  push:
    branches:
      - test-actions  
    paths:
      - ".github/workflows/pull-request-main.yml"

jobs:
  pull-request-on-main:
    runs-on: ubuntu-latest
    steps:
      - name: dry-run mode
        run: echo "Running app"
      - name: Clone repository
        run: |
          git clone https://github.com/cmramirezme/Scripting_challenge.git
          cd Scripting_challenge
          git checkout test-actions
      - name: Upload PDF report
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: pdf-report
          path: Scripting_challenge/out/*.{pdf,json}
          retention-days: 14
      - name: Summarize output
        run: |
          echo "## 📄 Reports Summary" >> $GITHUB_STEP_SUMMARY
          for f in Scripting_challenge/out/*.json; do
            count=$(jq length "$f")
            name=$(basename "$f" .json)
            echo "- $name: $count items" >> $GITHUB_STEP_SUMMARY
          done

