name: Test GitHub Secret

on:

  push:
    branches:
      - test-actions   # <-- tu rama actual
    paths:
      - ".github/workflows/test-secret.yml"
  workflow_dispatch:

jobs:
  test-secret:
  runs-on: ubuntu-latest
  steps:
    - name: Check if SMTP_PASS is set
      run: |
        if [ -z "${{ secrets.SMTP_PASS }}" ]; then
          echo "❌ Secret SMTP_PASS is not set."
          exit 1
        else
          echo "✅ Secret SMTP_PASS is set."
        fi

