name: Test GitHub Secret

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret is set
        run: |
          if [ -z "${{ secrets.SMTP_PASS }}" ]; then
            echo "❌ Secret MY_SECRET is not set."
            exit 1
          else
            echo "✅ Secret MY_SECRET is set."
          fi
